// Core scheduling logic — ported 1:1 from the original single-file HTML
// tool. These are plain functions operating on the plain data shapes
// (state, patternLib, holidays, groupRotations) instead of module-global
// mutable variables, so the React layer can own that state instead.

export const THAI_MONTHS = ["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"];
export const THAI_WEEKDAYS = ["อา","จ","อ","พ","พฤ","ศ","ส"]; // JS getDay(): 0=Sun
export const MAX_CYCLE = 31; // covers rotations up to roughly a month long
export const PREV_TAIL_DAYS = 5;
export const RECENT_WINDOW_DAYS = 21;

export function uid(){ return Math.random().toString(36).slice(2,10); }

export function defaultShiftCodes(){
  return [
    {code:"N10", start:"22:00", end:"07:00", color:"#312e81"},
    {code:"E2",  start:"14:00", end:"23:00", color:"#c2410c"},
    {code:"M6",  start:"06:00", end:"15:00", color:"#b45309"},
    {code:"MM6", start:"06:00", end:"19:00", color:"#0f766e"},
    {code:"EE6", start:"18:00", end:"07:00", color:"#6d28d9"},
    {code:"M8",  start:"08:00", end:"17:00", color:"#0369a1"},
    {code:"TH",  start:"", end:"", color:"#b91c1c"},
    {code:"LA",  start:"", end:"", color:"#57534e"}
  ];
}

export function ensureBuiltinCodes(st){
  // older saved months may predate the LA (ลาพักร้อน) code — add it if missing
  if(!st.shiftCodes.some(c=>c.code.toUpperCase()==="LA")){
    st.shiftCodes.push({code:"LA", start:"", end:"", color:"#57534e"});
  }
  return st;
}

export function defaultState(){
  const now = new Date();
  return {
    department: "สวนวิศวกรรมระบบเก็บเงินค่าผ่านทาง",
    month: now.getMonth()+1,
    yearBE: now.getFullYear()+543,
    autoGenerated:false,
    shiftCodes: defaultShiftCodes(),
    employees: [
      {id:uid(), empCode:"138015", name:"นายณัฐพล นาชัยสินธุ์", note:"062-7094212", days:{}, autoFlags:{}},
      {id:uid(), empCode:"142013", name:"นายภราดร กุมารจันทร์", note:"085-9112811", days:{}, autoFlags:{}}
    ]
  };
}

export const PATTERN_KEY = "shift-patterns-v1";
export const HOLIDAY_KEY = "holidays-v1";
export const ROTATION_KEY = "shift-group-rotations-v1";

export function storageKey(month, yearBE){ return "schedule:" + yearBE + "-" + String(month).padStart(2,"0"); }
export function patternKeyFor(emp){ return (emp.empCode && emp.empCode.trim()) || (emp.name && emp.name.trim()) || null; }

export function hexToRgb(hex){
  const h = hex.replace("#","");
  return [parseInt(h.slice(0,2),16), parseInt(h.slice(2,4),16), parseInt(h.slice(4,6),16)];
}
export function tint(hex, amount){
  const [r,g,b] = hexToRgb(hex);
  const mix = (c)=> Math.round(c + (255-c)*amount);
  return `rgb(${mix(r)},${mix(g)},${mix(b)})`;
}
export function tintHex(hex, amount){
  const [r,g,b] = hexToRgb(hex);
  const mix = (c)=> Math.round(c + (255-c)*amount);
  const toHex = (n)=> n.toString(16).padStart(2,"0").toUpperCase();
  return toHex(mix(r))+toHex(mix(g))+toHex(mix(b));
}
export function hexNoHash(hex){ return (hex||"000000").replace("#","").toUpperCase(); }

export function daysInMonth(yearBE, month1to12){
  const yearCE = yearBE - 543;
  return new Date(yearCE, month1to12, 0).getDate();
}
export function weekdayLabel(yearBE, month1to12, day){
  const yearCE = yearBE - 543;
  return THAI_WEEKDAYS[new Date(yearCE, month1to12-1, day).getDay()];
}
export function isWeekend(yearBE, month1to12, day){
  const yearCE = yearBE - 543;
  const wd = new Date(yearCE, month1to12-1, day).getDay();
  return wd === 0 || wd === 6;
}
export function weekdayIndexOf(yearBE, month1to12, day){
  const yearCE = yearBE - 543;
  return new Date(yearCE, month1to12-1, day).getDay(); // 0=Sun ... 6=Sat
}
export function globalDayIndex(yearBE, month1to12, day){
  const yearCE = yearBE - 543;
  return Math.round(Date.UTC(yearCE, month1to12-1, day) / 86400000);
}
export function nextMonthOf(month, yearBE){
  return month === 12 ? {month:1, yearBE: yearBE+1} : {month: month+1, yearBE};
}
export function prevMonthOf(month, yearBE){
  return month === 1 ? {month:12, yearBE: yearBE-1} : {month: month-1, yearBE};
}

export function parseCellValue(raw){
  if(!raw) return {base:"", wh:false, th:false, ot:false};
  const v = raw.trim().toUpperCase();
  if(v.endsWith("WH") && v.length>2){
    return {base:v.slice(0,-2), wh:true, th:false, ot:false};
  }
  if(v.endsWith("TH") && v.length>2){
    return {base:v.slice(0,-2), wh:false, th:true, ot:false};
  }
  if(v.endsWith("OT") && v.length>2){
    return {base:v.slice(0,-2), wh:false, th:false, ot:true};
  }
  return {base:v, wh:false, th:false, ot:false};
}

export function styleForCell(raw, shiftCodes){
  const {base, wh, th, ot} = parseCellValue(raw);
  const def = shiftCodes.find(c=>c.code.toUpperCase()===base);
  if(!def){
    if(base==="WH") return {bg:"#efece4", fg:"#6b645c", border:"none"};
    if(!base) return {bg:"transparent", fg:"var(--ink)", border:"none"};
    return {bg:"#f3f1ec", fg:"#8a8378", border:"none"};
  }
  const bg = tint(def.color, (wh||th) ? 0.55 : 0.86);
  let border = "none";
  if(wh) border = `2px dashed ${def.color}`;
  if(th) border = `2px dotted #b91c1c`;
  if(ot) border = `2px solid #db2777`;
  return {bg, fg:def.color, border};
}

/* ---------- shortcut-key expansion ----------
   Mirrors the VBA "Select Case inputValue" lookup: type a short code in a
   day cell, tab/click away (or press Enter), and it expands to the full
   shift code. Typing the full code directly still works as before. */
export const SHORTCUT_MAP = {
  // --- M series ---
  "6":"M6",  "6W":"M6WH",  "6T":"M6TH",  "6O":"M6OT",
  "8":"M8",  "8W":"M8WH",  "8T":"M8TH",  "8O":"M8OT",
  "MM":"MM6","MT":"MM6TH", "MO":"MM6OT",
  // --- E series ---
  "2":"E2",  "2W":"E2WH",  "2T":"E2TH",  "2O":"E2OT",
  "EE":"EE6","ET":"EE6TH", "EO":"EE6OT",
  // --- N series ---
  "10":"N10","10W":"N10WH","10T":"N10TH","10O":"N10OT",
  // --- leave ---
  "L":"LA"
};
export function expandShortcut(val){
  if(!val) return val;
  const key = val.trim().toUpperCase();
  return Object.prototype.hasOwnProperty.call(SHORTCUT_MAP, key) ? SHORTCUT_MAP[key] : key;
}

/* ---------- pattern detection ---------- */
export function isPatternWildcard(v){
  if(!v) return true;
  if(v === "LA") return true;
  if(v.endsWith("TH")) return true;
  if(v.endsWith("OT") && v.length>2) return true;
  return false;
}

export function wildcardFallbackBase(v){
  if(!v || !v.endsWith("TH") || v.length<=2) return null;
  const base = v.slice(0, -2);
  if(!base || base === "WH") return null;
  return base;
}

export function detectCycle(daysArray){
  const n = daysArray.length;
  const nonBlank = daysArray.filter(v=>!isPatternWildcard(v));
  if(nonBlank.length < Math.max(3, Math.floor(n*0.4))) return null; // not enough data

  const maxTrustedL = Math.max(1, Math.floor(n/2));
  for(let L=1; L<=Math.min(MAX_CYCLE, maxTrustedL); L++){
    const phases = new Array(L).fill(null);
    let ok = true;
    for(let i=0; i<n && ok; i++){
      const v = daysArray[i];
      if(isPatternWildcard(v)) continue;
      const p = i % L;
      if(phases[p] === null){
        phases[p] = v;
      } else if(phases[p] !== v){
        ok = false;
      }
    }
    if(ok && phases.some(p=>p!==null)){
      for(let p=0; p<L; p++){
        if(phases[p] !== null) continue;
        for(let i=p; i<n; i+=L){
          const fb = wildcardFallbackBase(daysArray[i]);
          if(fb){ phases[p] = fb; break; }
        }
      }
      const cycle = phases.map(p=>p===null? "" : p);
      return {length:L, cycle, confidence:"high"};
    }
  }
  const cycle = daysArray.map(v=> (isPatternWildcard(v) ? (wildcardFallbackBase(v) || "") : v));
  return {length:n, cycle, confidence:"low"};
}

export function phaseValue(pattern, yearBE, month, day){
  const anchorDay = pattern.anchorDay || 1;
  const idx = globalDayIndex(yearBE, month, day) - globalDayIndex(pattern.anchorYearBE, pattern.anchorMonth, anchorDay);
  const L = pattern.length;
  const phase = ((idx % L) + L) % L;
  return pattern.cycle[phase] || "";
}

/* ---------- leave (LA) & mandatory-OT coverage suggestion ---------- */
export function isOvernightCode(codeBase, shiftCodes){
  const def = shiftCodes.find(c=>c.code.toUpperCase()===codeBase);
  if(!def || !def.start || !def.end) return false;
  return def.start > def.end; // e.g. "22:00" > "07:00" crosses midnight
}

export function computeOtCounts(state){
  const counts = {};
  const nd = daysInMonth(state.yearBE, state.month);
  state.employees.forEach(emp=>{
    const key = patternKeyFor(emp) || emp.id;
    let c = 0;
    for(let d=1; d<=nd; d++){
      const {ot} = parseCellValue(emp.days[d]);
      if(ot) c++;
    }
    counts[key] = c;
  });
  return counts;
}

export function vacatedShiftFor(emp, day, state, patternLib){
  const key = patternKeyFor(emp);
  const pattern = key ? patternLib[key] : null;
  if(pattern) return phaseValue(pattern, state.yearBE, state.month, day);
  return "";
}

export function findOtCandidates(leaveEmp, day, vacatedBase, groupFilter, state){
  const otCounts = computeOtCounts(state);
  const list = state.employees
    .filter(e=>(!leaveEmp || e.id!==leaveEmp.id) && !e.excludeFromOt)
    .filter(e=>!groupFilter || (e.shiftGroup||"").trim()===groupFilter)
    .map(e=>{
      const todayRaw = (e.days[day]||"").trim().toUpperCase();
      const {base:todayBase, wh:todayWh} = parseCellValue(todayRaw);
      const prevRaw = day>1 ? (e.days[day-1]||"").trim().toUpperCase() : "";
      const {base:prevBase} = parseCellValue(prevRaw);
      const prevOvernight = !!(prevBase && isOvernightCode(prevBase, state.shiftCodes));
      const alreadySameShift = todayBase === vacatedBase && !todayWh;
      const onLeaveToday = todayBase === "LA";
      const key = patternKeyFor(e) || e.id;
      return { emp:e, todayBase, todayWh, prevOvernight, alreadySameShift, onLeaveToday, otCount: otCounts[key] || 0 };
    })
    .filter(c => !c.onLeaveToday && !c.alreadySameShift);

  list.sort((a,b)=>{
    const aOff = (a.todayWh || !a.todayBase) ? 0 : 1;
    const bOff = (b.todayWh || !b.todayBase) ? 0 : 1;
    if(aOff !== bOff) return aOff - bOff;
    if(a.prevOvernight !== b.prevOvernight) return (a.prevOvernight?1:0) - (b.prevOvernight?1:0);
    return a.otCount - b.otCount;
  });
  return list.slice(0,5);
}

/* ---------- holidays ---------- */
export function isHoliday(yearBE, month, day, holidays){
  return holidays.find(h => h.month===month && h.day===day && (h.year===null || h.year===yearBE)) || null;
}

export function defaultHolidays(){
  return [
    {id:uid(), month:1,  day:1,  year:null, name:"วันขึ้นปีใหม่"},
    {id:uid(), month:4,  day:6,  year:null, name:"วันจักรี"},
    {id:uid(), month:4,  day:13, year:null, name:"วันสงกรานต์"},
    {id:uid(), month:4,  day:14, year:null, name:"วันสงกรานต์"},
    {id:uid(), month:4,  day:15, year:null, name:"วันสงกรานต์"},
    {id:uid(), month:5,  day:1,  year:null, name:"วันแรงงานแห่งชาติ"},
    {id:uid(), month:7,  day:28, year:null, name:"วันเฉลิมพระชนมพรรษา ร.10"},
    {id:uid(), month:8,  day:12, year:null, name:"วันแม่แห่งชาติ"},
    {id:uid(), month:10, day:13, year:null, name:"วันคล้ายวันสวรรคต ร.9"},
    {id:uid(), month:10, day:23, year:null, name:"วันปิยมหาราช"},
    {id:uid(), month:12, day:5,  year:null, name:"วันพ่อแห่งชาติ"},
    {id:uid(), month:12, day:10, year:null, name:"วันรัฐธรรมนูญ"},
    {id:uid(), month:12, day:31, year:null, name:"วันสิ้นปี"},
  ];
}

export function addCompensatoryWH(emp, fromDay, nd, state, holidays){
  for(let d=fromDay+1; d<=nd; d++){
    const raw = (emp.days[d]||"").trim().toUpperCase();
    const {base, wh, th, ot} = parseCellValue(raw);
    if(wh || th || ot || base==="LA") continue;
    if(isHoliday(state.yearBE, state.month, d, holidays)) continue;
    emp.days[d] = base ? (base+"WH") : "WH";
    emp.autoFlags[d] = true;
    return d;
  }
  return null;
}

export function applyHolidayOverridesForMonth(state, holidays){
  const nd = daysInMonth(state.yearBE, state.month);
  let converted = 0, compensated = 0, unplaced = 0;
  for(let d=1; d<=nd; d++){
    const hol = isHoliday(state.yearBE, state.month, d, holidays);
    if(!hol) continue;
    state.employees.forEach(emp=>{
      if(!emp.autoFlags) emp.autoFlags = {};
      const raw = (emp.days[d]||"").trim().toUpperCase();
      if(!raw) return;
      const {base, wh, th, ot} = parseCellValue(raw);
      if(!base || base==="LA" || th || ot) return;
      const newVal = base + "TH";
      if(raw !== newVal){
        emp.days[d] = newVal;
        emp.autoFlags[d] = true;
        converted++;
      }
      if(wh){
        const placedAt = addCompensatoryWH(emp, d, nd, state, holidays);
        if(placedAt) compensated++; else unplaced++;
      }
    });
  }
  return {converted, compensated, unplaced};
}

/* ---------- rotating weekly off-day pair per shift group ---------- */
export function rotationPairForGroup(groupKey, groupRotations, state){
  const cfg = groupRotations[groupKey];
  if(!cfg) return null;
  const monthsSince = (state.yearBE*12 + state.month) - (cfg.anchorYearBE*12 + cfg.anchorMonth);
  const step = cfg.stepDays || 2;
  let start = (cfg.anchorStartDay + step*monthsSince) % 7;
  if(start < 0) start += 7;
  return [start, (start+1) % 7];
}

export function applyGroupRotationsForMonth(state, groupRotations, holidays){
  const nd = daysInMonth(state.yearBE, state.month);
  let placed = 0, reverted = 0, skippedHoliday = 0;
  const groupsApplied = [];
  Object.keys(groupRotations).forEach(groupKey=>{
    const cfg = groupRotations[groupKey];
    const pair = rotationPairForGroup(groupKey, groupRotations, state);
    if(!pair) return;
    groupsApplied.push({group:groupKey, pair});
    const memberKeys = cfg.memberKeys || [];
    const members = state.employees.filter(e=>{
      const k = patternKeyFor(e);
      return k && memberKeys.includes(k);
    });
    members.forEach(emp=>{
      if(!emp.autoFlags) emp.autoFlags = {};
      if(!emp.rotationFlags) emp.rotationFlags = {};
      for(let d=1; d<=nd; d++){
        const wd = weekdayIndexOf(state.yearBE, state.month, d);
        const inPair = pair.includes(wd);
        const raw = (emp.days[d]||"").trim().toUpperCase();
        const {base, wh, th, ot} = parseCellValue(raw);
        if(inPair){
          if(isHoliday(state.yearBE, state.month, d, holidays)){ skippedHoliday++; continue; }
          if(th || ot || base==="LA") continue;
          const newVal = base ? (base+"WH") : "WH";
          if(raw !== newVal){
            emp.days[d] = newVal;
            emp.autoFlags[d] = true;
            emp.rotationFlags[d] = true;
            placed++;
          }
        } else if(wh && emp.rotationFlags[d]){
          emp.days[d] = base || "";
          delete emp.autoFlags[d];
          delete emp.rotationFlags[d];
          reverted++;
        }
      }
    });
  });
  return {placed, reverted, skippedHoliday, groupsApplied};
}

/* ---------- fill 3-shift rotation gaps (MM6 / EE6) ---------- */
export function fixThreeShiftGaps(state){
  const nd = daysInMonth(state.yearBE, state.month);
  const ORDER = ["M6","E2","N10"];
  const groups = {};
  state.employees.forEach(emp=>{
    const g = (emp.shiftGroup||"").trim();
    if(!g) return;
    (groups[g] = groups[g]||[]).push(emp);
  });

  let converted = 0, otWarnings = 0;
  const log = [];

  Object.keys(groups).forEach(groupName=>{
    const members = groups[groupName];
    for(let d=1; d<=nd; d++){
      const todayInfo = members.map(emp=>{
        const raw = (emp.days[d]||"").trim().toUpperCase();
        const {base, wh, th, ot} = parseCellValue(raw);
        return {emp, base, working: !!(base && !wh && !th && !ot && base!=="LA")};
      });
      const present = new Set(todayInfo.filter(t=>t.working).map(t=>t.base));
      const missing = ORDER.filter(code=>!present.has(code));
      if(missing.length !== 1) continue;
      const missingCode = missing[0];
      const dateLabel = `วันที่ ${d} (${weekdayLabel(state.yearBE, state.month, d)})`;

      if(missingCode === "N10"){
        otWarnings++;
        const candidates = findOtCandidates(null, d, "N10", groupName, state);
        log.push({type:"ot-warning", group:groupName, dateLabel, day:d, candidates});
        continue;
      }

      const [earlyCode, lateCode] = ORDER.filter(code=>code!==missingCode);
      const earlyWorker = todayInfo.find(t=>t.working && t.base===earlyCode);
      const lateWorker = todayInfo.find(t=>t.working && t.base===lateCode);
      const did = [];
      if(earlyWorker){
        earlyWorker.emp.days[d] = "MM6";
        if(!earlyWorker.emp.autoFlags) earlyWorker.emp.autoFlags = {};
        earlyWorker.emp.autoFlags[d] = true;
        converted++;
        did.push(`${earlyWorker.emp.name||earlyWorker.emp.empCode}: ${earlyCode}→MM6`);
      }
      if(lateWorker){
        lateWorker.emp.days[d] = "EE6";
        if(!lateWorker.emp.autoFlags) lateWorker.emp.autoFlags = {};
        lateWorker.emp.autoFlags[d] = true;
        converted++;
        did.push(`${lateWorker.emp.name||lateWorker.emp.empCode}: ${lateCode}→EE6`);
      }
      log.push({
        type:"converted", group:groupName, dateLabel, missingCode,
        result: did.length ? did.join(", ") : "ไม่พบคนทำกะที่จะปรับให้ (ไม่มีใครทำงานในกะที่เหลือวันนั้น)"
      });
    }
  });
  return {converted, otWarnings, groupCount: Object.keys(groups).length, log};
}
